NethServer/nethserver-ns8-migration

- createlinks
The WireGuard tunnel is unresponsive when interface-update is signaled. The wg0 restart should fix the problem.
> interface-update. Restart wg0 VPN

- root/usr/share/nethesis/nethserver-ns8-migration/apps/nethserver-webtop5/bind.env
- root/usr/share/nethesis/nethserver-ns8-migration/apps/nethserver-webtop5/migrate
If the db prop `ActiveSyncLegacyIds` is enabled, the value will be preserved in the migration.
Related PR: NethServer/ns8-webtop#13
> Add z-push state directory in the webtop migration

- root/usr/share/nethesis/nethserver-ns8-migration/apps/nethserver-mail/bind.env
- root/usr/share/nethesis/nethserver-ns8-migration/apps/nethserver-mail/migrate
The volume is not created any more by create-module. Wait until it is properly initialized by Podman, then merge contents into it.
Migrate the Redis dump.rdb to its final location as the volume is empty and rspamd is stopped by default.
> Fix migration of rspamd-data in nethserver-mail

- root/etc/e-smith/templates/var/lib/machines/nsdc/etc/systemd/network/green.network/20wg_route
- root/usr/sbin/ns8-join
- root/usr/sbin/ns8-leave
- root/usr/share/nethesis/nethserver-ns8-migration/apps/account-provider/ad/bind.env
- root/usr/share/nethesis/nethserver-ns8-migration/apps/account-provider/ad/migrate
* join: do not use CIDR notation for samba
* setup route for nsdc
Requires: https://github.com/NethServer/ns8-samba/pull/11
Before merge, update Samba image to latest available tag.
See also https://trello.com/c/c9CGnMdR/331-migration-tool-p1-test-openldap-and-samba-migration
> Fix samba migration

- api/migration/ad-helper
- api/migration/read
- root/usr/share/nethesis/nethserver-ns8-migration/apps/account-provider/ad/migrate
- root/usr/share/nethesis/nethserver-ns8-migration/apps/account-provider/input-finish.jq
- ui/src/views/Dashboard.vue
Allow to change the IP address during migration:
the NS8 node could not have the same IP address of the original server
Usage example:
```
echo '{"app":"account-provider","action":"finish", "migrationConfig": {"sambaIpAddress": "10.133.0.5"}}' | /usr/libexec/nethserver/api/nethserver-ns8-migration/migration/update
```
https://trello.com/c/c9CGnMdR/331-migration-tool-p1-test-openldap-and-samba-migration
> samba: support IP address parameters

- api/migration/update
- root/usr/sbin/ns8-check-import
Since the new command is called from the UI,
it assumes that NS8 connection is already up
because the list action has already been called.
See https://trello.com/c/pazffyzl/220-migtool-p2-migration-tool-exceptions
> api: resume rsync server

- api/migration/read
- api/migration/update
- root/usr/sbin/ns8-toggle-skip
- ui/public/i18n/language.json
- ui/src/views/Dashboard.vue
The "Skip migration" button is available only for applications. It is enabled only if:
- the migration of the app has not been already started
- the account provider migration has not been started
The account provider can be migrated when all applications are migrated or skipped.
See https://trello.com/c/kppKjWYd/334-migration-p2-skip-applications
Screencast: [Screencast from 2023-03-21 16-46-56.webm](https://user-images.githubusercontent.com/804596/226670504-89d85a67-1679-4a33-8113-8a5f33df1dc6.webm)
> api & ui: allow application skip

- api/migration/update
- ui/src/views/Dashboard.vue
Reference: https://trello.com/c/OAQ51D2b/349-migtool-p-abort-does-not-work-with-webtop-and-roundcube
WebTop and Roundcube migration can't be skipped. If the user doesn't want them, it must delete the app on NS8 after migration.
Before starting the migration:
During migration:
Skipped migration:
> Manage mail group all together

- root/usr/share/nethesis/nethserver-ns8-migration/apps/nethserver-ejabberd/migrate
- root/usr/share/nethesis/nethserver-ns8-migration/apps/nethserver-mattermost/migrate
- root/usr/share/nethesis/nethserver-ns8-migration/apps/nethserver-nextcloud/migrate
the migration path of some module is broken when we require to chown the data synchronized by rsync
the options `--owner --group --chown=2000:2000` are not honored anymore. It comes probably from the different version in alpine (3.2.7) and NS7 (3.1.2)
reading the documentation the `--chown` is a shortcut to `--usermap=*:foo --groupmap=*:bar`. It seems if we add the `s` (advised by the documentation), rsync does the correct chown for the migration
https://trello.com/c/3r7hU8Qm/379-fix-bad-ownership-with-rsync-migration
https://download.samba.org/pub/rsync/rsync.1#opt--chown
> rsync on ns7 does not expand wildcard of --chown

- api/connection/validate
- ui/public/i18n/language.json
From https://trello.com/c/3d7gT1JO/448-migration-p0-e-smith-db-corrupt-with-pipe-char
The Pipe character inside a password field can break the e-smith database we need to validate that this character is not used. It is then required that the remote password does not contain `|` (pipe) characters
> Password validation, avoid pipe character

- root/usr/share/nethesis/nethserver-ns8-migration/apps/nethserver-mail-getmail/migrate
This pull request disables the getmail service and updates the configuration. The getmail service is now disabled and the getmail configuration has been expanded with the disabled status. This change ensures that the getmail service is no longer active.
https://github.com/NethServer/dev/issues/6776
> Disable getmail service and update configuration

- api/migration/read
This pull request fixes the condition in the code that checks for the existence of the roundcubemail mariadb  directory. The previous condition was checking for a esmith file instead of a directory and we could make a mistake with nethserver-roundcubemail-next
This caused incorrect results in certain cases. The fix ensures that the correct check is performed
https://github.com/NethServer/dev/issues/6851
> Fix condition to check for roundcubemail mariadb  directory existence

- api/migration/update
- root/usr/share/nethesis/nethserver-ns8-migration/apps/nethserver-mail/bind
This commit fixes the migration script to handle the existence of the roundcubemail directory. Previously, the script only checked for the existence of the roundcubemail configuration file, but now it also checks for the existence of the directory. This ensures that the migration process works correctly in all scenarios.
https://github.com/NethServer/dev/issues/6851
> Fix migration script to handle roundcubemail directory existence

- ui/src/views/Dashboard.vue
This pull request fixes the migration detection of the webtop virtualhost. Previously, the migration would only set the webtop virtualhost if it was not already set. However, this caused an issue when the webtop virtualhost was already set in the Nextcloud app configuration. This pull request updates the migration to check if the webtop virtualhost is already set in the Nextcloud app configuration and uses it if available.
https://github.com/NethServer/dev/issues/6851
> Fix migration detection of webtop virtualhost

- root/usr/share/nethesis/nethserver-ns8-migration/apps/nethserver-nethvoice14/migrate
- ui/public/i18n/language.json
- ui/src/views/Dashboard.vue
This pull request fixes the indentation in the `phonebook_db_password` field and also fixes the validation for the `nethvoice` and `cti` virtual hosts.
validate the virtualhost of cti and nethvoice 
https://github.com/NethServer/dev/issues/6872
> Fixes the validator in nethvoiceApp

- ui/src/views/Dashboard.vue
This pull request fixes the condition in the Dashboard.vue file that checks for the presence of the webtopApp virtual host. Previously, the condition was not properly checking for the existence of the webtopApp object, leading to potential errors. This fix ensures that the condition accurately checks for the webtopApp virtual host before proceeding with the migration configuration.
We cannot migrate the stack because I introduced a bug when webtop is not installed, we look after a json object not initialized 
https://github.com/NethServer/dev/issues/6876
> Fix condition to check for webtopApp virtual host

- root/usr/share/nethesis/nethserver-ns8-migration/apps/nethserver-mail/migrate
This pull request adds the networks.json file to the mail migration script, allowing for the synchronization of network configurations during the migration process.
refs: NethServer/dev#6895
> Add networks.json to the mail migration script

- root/usr/share/nethesis/nethserver-ns8-migration/apps/nethserver-mail/migrate
This pull request adds the SmartHost configuration to the mail migration script. The script now checks if the SmartHostStatus is enabled and sets the appropriate configuration for the SmartHost. This ensures that the mail module can communicate with the SmartHost properly during the migration process.
tested with ghcr.io/nethserver/core:2.8.0-dev.1 and ghcr.io/nethserver/mail:sdl-6895-import-NS7-credentials
NethServer/dev#6895
linked to https://github.com/NethServer/ns8-mail/pull/113
> Add SmartHost configuration to mail migration script

- root/usr/share/nethesis/nethserver-ns8-migration/apps/account-provider/ldap/migrate
This pull request adds the `displayName` attribute to the users copied from `gecos` during the migration process. The `displayName` attribute was missing in the `dump-mdb0.ldif` file, so this PR includes a patch that adds it manually.
at the end the display name is populated after the migration
the sed command copy from gecos field the value and add it to the displayName field, at the end we add
```
+ displayName: john foo
gecos: john foo
```
https://github.com/NethServer/dev/issues/6930
> Add displayName attribute to users copied from gecos

- api/connection/update
- api/migration/update
- root/usr/sbin/ns8-join
- root/usr/sbin/ns8-leave
This pull request adds error handling for failed external domain addition. If the external domain cannot be added, the cluster will be left using the `/usr/sbin/ns8-leave` command.
https://github.com/NethServer/dev/issues/6985
when the error comes
what you find in logs 
```
=========== Join cluster Fri, 02 Aug 2024 10:17:47 +0200
=========== Leave cluster Fri, 02 Aug 2024 10:17:56 +0200
{"steps":2,"pid":23770,"args":"","event":"nethserver-ns8-migration-save"}
{"step":1,"pid":23770,"action":"S05generic_template_expand","event":"nethserver-ns8-migration-save","state":"running"}
{"progress":"0.50","time":"0.05514","exit":0,"event":"nethserver-ns8-migration-save","state":"done","step":1,"pid":23770,"action":"S05generic_template_expand"} …
```
> Add error handling for failed external domain addition

- root/usr/sbin/ns8-join
- root/usr/sbin/ns8-leave
The ns8-join script has been updated to check for an existing user before joining and to create the ns7admin user and handle failure gracefully. The ns8-leave script has been updated to remove the ns7admin user when leaving the cluster. These changes ensure that the scripts function correctly and improve the overall stability of the system.
https://github.com/NethServer/dev/issues/6994
> Use ns7admin for migration

- root/usr/sbin/ns8-join
- root/usr/sbin/ns8-leave
To handle a scenario where we migrate two nodes at the same times, we need to get two ns7admin else we will have a conflict. the solution is to add the node_id that is specific to the migration, each connection to the same cluster will increment the node_id
https://github.com/NethServer/dev/issues/6994
> Add the node_id to the ns7admin user

- root/usr/sbin/ns8-leave
This pull request fixes an issue in the `ns8-leave` script where the `ns7admin` user was not being removed correctly when the node ID was passed as a digit. The patch updates the script to remove the user using the correct format for the node ID.
https://github.com/NethServer/dev/issues/6994
> Fix ns8-leave script to remove ns7admin user with node ID as a string

- README.rst
This pull request  documents how to enable back SOGo after a failed NS8 migration. 
The migration process was unsuccessful, and this commit document host to  SOGo is re-enabled by setting the `sogod` status to enabled and triggering the `nethserver-sogo-update` event.
> Enable SOGo after failed NS8 migration

- ui/src/views/Dashboard.vue
This pull request updates the `Dashboard.vue` file to prevent to let the UI blocked when apps without account provider have been `migrated`.
Previously, the option to disconnect was not shown anymore  when an app has been seen  `migrated`, leading to potential issues. With this change, the option to disconnect will be shown 
if the account provider is not present 
or 
if apps have the status `migrated` and the account provider is present (remote or local)
https://github.com/NethServer/dev/issues/7005
tested cases 
- mattermost and/or nextcloud without account provider
- mattermost and nextcloud with an account provider
- mattermost and nextcloud with a remote account provider
The solution is not optimal, the user needs to click on the link `connect to a different cluster` but at least the …
> Prevent stopping migration if account provider is not migrated

- root/usr/share/nethesis/nethserver-ns8-migration/apps/nethserver-webtop5/migrate
This pull request adds the "AdminMail" field to the migration script for the "nethserver-webtop5" app. The field is set to a default value of an empty string.
https://github.com/NethServer/dev/issues/6984
> Add AdminMail to migration with default value

- ui/src/views/Dashboard.vue
This pull request enables 
- the migration of the account provider even if it has a "not_available" status. Previously, the migration was only allowed for certain statuses, but now it can be performed regardless of the status.
- It prevents migrating the account provider before the Netvoice app.
https://github.com/NethServer/dev/issues/7037
> Allow migration of account provider with "not_available" status

- ui/public/i18n/language.json
This pull request adds a new entry in the `language.json` file to include a destination node for the POP3/IMAP Connector.
> Add destination node for POP3/IMAP Connector in language.json

- api/connection/read
- api/connection/update
- api/connection/validate
- root/usr/sbin/ns8-join
- root/usr/share/nethesis/nethserver-ns8-migration/apps/account-provider/ldap/migrate
- root/usr/share/nethesis/nethserver-ns8-migration/apps/nethserver-ejabberd/migrate
- root/usr/share/nethesis/nethserver-ns8-migration/apps/nethserver-nextcloud/migrate
- root/usr/share/nethesis/nethserver-ns8-migration/apps/nethserver-sogo/migrate
- ui/public/i18n/language.json
- ui/src/views/Dashboard.vue
Update the LDAP configuration and migration scripts to utilize a fully qualified domain name (FQDN) given by the sysadmin,  instead of the hardcoded value directory.nh, enhancing flexibility and accuracy in domain handling.
https://github.com/NethServer/dev/issues/7103
> Use a FQDN for LDAP domain and migration scripts instead of directory.nh

- root/usr/share/nethesis/nethserver-ns8-migration/apps/nethserver-nextcloud/bind.env
Update the Nextcloud module to use the latest image version 1.1.9.
https://github.com/NethServer/dev/issues/7103
> Migrate Nextcloud module image to version 1.1.9

- api/connection/read
- ui/public/i18n/language.json
- ui/src/views/Dashboard.vue
Enhance the connection configuration by incorporating the LDAP user domain and improving the UI for better readability.
https://github.com/NethServer/dev/issues/7103
> Include LDAP user domain in connection configuration

- root/usr/sbin/ns8-join
- root/usr/share/nethesis/nethserver-ns8-migration/apps/nethserver-nethvoice14/bind
Test if the nethvoice proxy is installed on the node where we migrate nethserver-nethvoice14
Install on the ns8 node only if missing 
- we trigger list-modules action each time the bind for nethvoice is triggered
- we check, can we install  on the node where we migrate nethvoice
- if true we install the proxy
https://github.com/NethServer/dev/issues/7221
> Install nethvoice-proxy during nethvoice migration

- api/migration/read
- ui/public/i18n/language.json
- ui/src/views/Dashboard.vue
Implement checks to determine if mail and ejabberd are installed on nodes, enhancing the dashboard to reflect this status and providing user feedback for already installed components.
in case of a single node 
https://github.com/NethServer/dev/issues/7226
> Add installation checks for mail and ejabberd on nodes

- api/migration/read
- root/usr/sbin/ns8-join
- ui/public/i18n/language.json
- ui/src/views/Dashboard.vue
Implement checks for Active Directory provider installation on cluster nodes and enhance the dashboard to allow node selection for AD applications based on installation status.
https://github.com/NethServer/dev/issues/7226
if we have no node available, now we cannot login anymore
if we succeed to login but someone starts to install a AD on the NS8 after you succeed to login
when we have a node available
in case of a cluster with only one node 
https://github.com/user-attachments/assets/3eb4966f-4f1c-4176-92be-9157209f17bc
https://github.com/user-attachments/assets/b0480ae0-970a-4af1-aa64-0cbd89f46a93
for now there is no check about if dnsmasq is installed with dns server enabled
> Add AD provider installation checks for cluster nodes and dashboard selection

- ui/src/views/Dashboard.vue
We need to handle the case where an active directory has been added after the join to the cluster, now we completely block the scenario. However once joined and when we have started a migration, no way back, the only thing to do is to add a new node or remove the AD on one node
https://github.com/NethServer/dev/issues/7226
https://github.com/user-attachments/assets/78e873d3-a55f-45a0-9f49-39d436b80257
https://github.com/user-attachments/assets/73cf1325-0a62-4ec2-8a0e-efecf80b62f2
> Add error handling for unavailable nodes in Samba provider

- root/usr/share/nethesis/nethserver-ns8-migration/apps/nethserver-webtop5/migrate
If the admin force the IMAP server to localhost, after the migration the user will not be able to access the server.
NethServer/dev#7371
> feat(webtop): cleanup IMAP config

- ui/src/views/Dashboard.vue
Ensure the abort action in the Dashboard correctly handles the migration log with sudo rights.
https://github.com/NethServer/dev/issues/7449
> Fix abort action requiring sudo rights for migration log

- root/usr/share/nethesis/nethserver-ns8-migration/apps/nethserver-nethvoice14/migrate
If fias isn't installed on nethvoice, migration fails:
```
rsync: link_stat "/etc/fias.conf" failed: No such file or directory (2)"
```
> fix(nethvoice): Don't fail if /etc/fias.conf doesn't exist

- root/usr/share/nethesis/nethserver-ns8-migration/apps/nethserver-webtop5/bind.env
This pull request updates the image URL for the `webtop` module in the `bind.env` configuration file to use a specific version to avoid the posgresql upgrade directly
The Upgrade from 9 to postgres 17 fails in the import-module action
https://github.com/NethServer/dev/issues/7489
> Update bind.env to webtop 1.4.4
